package gocli

import (
	"fmt"
	"html"
	"strings"
)

type CommandReferenceSection struct {
	ID     string
	Title  string
	Source string
	Help   string
}

func CommandReferenceSections() []CommandReferenceSection {
	return []CommandReferenceSection{
		{
			ID:     "top-level",
			Title:  "Top-level command map",
			Source: "nana help",
			Help:   TopLevelHelp,
		},
		{
			ID:     "work",
			Title:  "Work runtime",
			Source: "nana help work",
			Help:   WorkHelp,
		},
		{
			ID:     "issue",
			Title:  "GitHub issue aliases",
			Source: "nana help issue",
			Help:   IssueHelp,
		},
		{
			ID:     "investigate",
			Title:  "Investigation workflow",
			Source: "nana help investigate",
			Help:   InvestigateHelp,
		},
		{
			ID:     "repo",
			Title:  "Repo onboarding and policies",
			Source: "nana help repo",
			Help:   RepoHelp,
		},
		{
			ID:     "review",
			Title:  "GitHub PR review workflow",
			Source: "nana help review",
			Help:   GithubReviewHelp,
		},
		{
			ID:     "review-rules",
			Title:  "GitHub review rules",
			Source: "nana help review-rules",
			Help:   ReviewRulesHelp,
		},
		{
			ID:     "start",
			Title:  "Repo automation",
			Source: "nana help start",
			Help:   StartHelp,
		},
		{
			ID:     "improve",
			Title:  "Improvement scout",
			Source: "nana help improve",
			Help:   ImproveHelp,
		},
		{
			ID:     "enhance",
			Title:  "Enhancement scout",
			Source: "nana help enhance",
			Help:   EnhanceHelp,
		},
	}
}

func RenderCommandReferenceHTML() string {
	var builder strings.Builder
	builder.WriteString(`<!doctype html>
<!-- Generated by go run ./cmd/nana-docs; do not edit by hand. -->
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>CLI Command Reference - nana Docs</title>
    <link rel="stylesheet" href="./style.css" />
  </head>
  <body>
    <header>
      <nav class="container nav" aria-label="Primary">
        <a class="brand" href="./index.html">nana</a>
        <a href="./index.html">Home</a>
        <a href="./getting-started.html">Getting Started</a>
        <a class="active" href="./command-reference.html">CLI Reference</a>
        <a href="./work.md">Work</a>
        <a href="./agents.html">Agents</a>
        <a href="./skills.html">Skills</a>
        <a href="./integrations.html">Integrations</a>
      </nav>
    </header>

    <main class="container">
      <h1>CLI Command Reference</h1>
      <p class="muted">
        Generated from Nana's checked-in CLI help constants. Regenerate with
        <code>go run ./cmd/nana-docs</code> after help text changes.
      </p>
      <p>
        For implementation runtime details, storage layout, and validation controls, see the
        <a href="./work.md">Work guide</a>.
      </p>

      <h2>Sections</h2>
      <ul>
`)
	for _, section := range CommandReferenceSections() {
		fmt.Fprintf(&builder, `        <li><a href="#%s">%s</a> - <code>%s</code></li>
`, html.EscapeString(section.ID), html.EscapeString(section.Title), html.EscapeString(section.Source))
	}
	builder.WriteString(`      </ul>
`)

	for _, section := range CommandReferenceSections() {
		fmt.Fprintf(&builder, `
      <section aria-labelledby="%s">
        <h2 id="%s">%s</h2>
        <p class="muted">Source: <code>%s</code></p>
        <pre><code>%s</code></pre>
      </section>
`, html.EscapeString(section.ID), html.EscapeString(section.ID), html.EscapeString(section.Title), html.EscapeString(section.Source), escapeCodeText(strings.TrimRight(section.Help, "\n")))
	}

	builder.WriteString(`
    </main>

    <footer>
      <div class="container">
        <span class="muted">This page mirrors CLI help; run <code>nana help [command]</code> for local output.</span>
      </div>
    </footer>
  </body>
</html>
`)
	return builder.String()
}

func escapeCodeText(value string) string {
	return strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;").Replace(value)
}
